# Generated by Django 4.2.4 on 2023-11-22 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_statementofapplicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='user',
            # field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            field=models.ForeignKey(
            to=settings.AUTH_USER_MODEL,
            on_delete=models.CASCADE,
            null=True,  
            ),
        ),
        migrations.AlterUniqueTogether(
            name='presentpositioninfo',
            unique_together={('user',)},
        ),
    ]
