# Generated by Django 4.2.4 on 2023-11-23 07:10


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_specialization_user_and_more'),
    ]

    operations = [
        # ... other operations ...

        # Remove the old user_id field
        migrations.RemoveField(
            model_name='specialization',
            name='user',
        ),

        # Add the new user field
        migrations.AddField(
            model_name='specialization',
            name='user',
            field=models.ForeignKey(
                to=settings.AUTH_USER_MODEL,
                on_delete=models.CASCADE,
                null=True,
            ),
        ),
    ]
